#!/bin/bash

d=heterosis_0.0.0

mkdir -p $d
mkdir -p $d/data/
mkdir -p $d/data/test
mkdir -p $d/inst
mkdir -p $d/R
mkdir -p $d/src

cp configure $d
cp data/test/smallData.txt $d/data/test
cp data/test/smallGroup.txt $d/data/test
cp data/exampleData.rda $d/data/exampleData.rda
cp data/exampleGroup.rda $d/data/exampleGroup.rda
cp DESCRIPTION $d
cp -r include $d
cp -r inst/doc $d/inst
cp Makefile $d
cp NAMESPACE $d
cp R/functions.r $d/R
cp -r src/cpu $d/src/cpu
cp -r src/gpu $d/src/gpu
cp -r src/Makefile_CPU $d/src/Makefile_CPU
cp -r src/Makefile_GPU $d/src/Makefile_GPU

tar -czf $d.tar.gz $d
rm -rf $d