#!/bin/bash

d=heterosis_0.0.0

mkdir -p $d
mkdir -p $d/data/
mkdir -p $d/data/test
mkdir -p $d/R

cp configure $d
cp data/test/smallData.txt $d/data/test
cp data/test/smallGroup.txt $d/data/test
cp data/exampleData.rda $d/data/exampleData.rda
cp data/exampleGroup.rda $d/data/exampleGroup.rda
cp DESCRIPTION $d
cp -r include $d
cp -r inst $d
cp NAMESPACE $d
cp R/functions.r $d/R
cp README $d
cp -r src $d

tar -czf $d.tar.gz $d
rm -rf $d
