% !TEX TS-program = knitr
\documentclass{article}

\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{caption}
\usepackage{color}
\usepackage{enumerate}
\usepackage{fancyhdr}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{latexsym}
\usepackage{listings}
\usepackage{mathrsfs}
\usepackage{natbib}
\usepackage[nottoc]{tocbibind}
\usepackage{url}

\providecommand{\all}{\ \forall \ }
\providecommand{\bs}{\backslash}
\providecommand{\e}{\varepsilon}
\providecommand{\E}{\ \exists \ }
\providecommand{\lm}[2]{\lim_{#1 \rightarrow #2}}
\providecommand{\m}[1]{\mathbb{#1}}
\providecommand{\nv}{{}^{-1}}
\providecommand{\ov}[1]{\overline{#1}}
\providecommand{\p}{\newpage}
\providecommand{\q}{$\quad$ \newline}
\providecommand{\rt}{\rightarrow}
\providecommand{\Rt}{\Rightarrow}
\providecommand{\vc}[1]{\boldsymbol{#1}}
\providecommand{\wh}[1]{\widehat{#1}}

%\renewcommand\bibname{References}
%\renewcommand{\thesection}{Problem \arabic{section}}
%\renewcommand{\thesubsection}{Part \alph{subsection}}

\fancyhead{}
\fancyfoot{}
\fancyhead[R]{\thepage}
\fancyhead[C]{Landau}

\hypersetup{
    colorlinks,
    citecolor=black,
    filecolor=black,
    linkcolor=black,
    urlcolor=blue
}

\definecolor{dkgreen}{rgb}{0,0.6,0}
\definecolor{gray}{rgb}{0.5,0.5,0.5}
\definecolor{mauve}{rgb}{0.58,0,0.82}

\lstset{ 
  language=C,                % the language of the code
  basicstyle=\Large,           % the size of the fonts that are used for the code
  numberstyle= \tiny \color{white},  % the style that is used for the line-numbers
  stepnumber=2,                   % the step between two line-numbers. 
  numbersep=5pt,                  % how far the line-numbers are from the code
  backgroundcolor=\color{white},      % choose the background color. You must add \usepackage{color}
  showspaces=false,               % show spaces adding particular underscores
  showstringspaces=false,         % underline spaces within strings
  showtabs=false,                 % show tabs within strings adding particular underscores
  frame=lrb,                   % adds a frame around the code
  rulecolor=\color{black},        % if not set, the frame-color may be changed on line-breaks within not-black text 
  tabsize=2,                      % sets default tabsize to 2 spaces
  captionpos=t,                   % sets the caption-position 
  breaklines=true,                % sets automatic line breaking
  breakatwhitespace=false,        % sets if automatic breaks should only happen at whitespace
  title=\lstname,                   % show the filename of files included with \lstinputlisting;
  keywordstyle=\color{blue},          % keyword style
  commentstyle=\color{gray},       % comment style
  stringstyle=\color{dkgreen},         % string literal style
  escapeinside={\%*}{*)},            % if you want to add LaTeX within your code
  morekeywords={*, ...},               % if you want to add more keywords to the set
  xleftmargin=0.053in, % left horizontal offset of caption box
  xrightmargin=-.03in % right horizontal offset of caption box
}

\DeclareCaptionFont{white}{\color{white}}
\DeclareCaptionFormat{listing}{\parbox{\textwidth}{\colorbox{gray}{\parbox{\textwidth}{#1#2#3}}\vskip-0.05in}}
\captionsetup[lstlisting]{format = listing, labelfont = white, textfont = white}
% For caption-free listings, comment out the 3 lines above and uncomment the 2 lines below.
% \captionsetup{labelformat = empty, labelsep = none}
% \lstset{frame = single}

<<echo = F>>=
options(width = 60) # R output width
@

\begin{document}
\begin{titlepage}
\begin{center}

\vspace*{4cm}
\hrule 
\vspace{0.4cm}
{ \huge \bfseries A Fully Bayesian Model for RNA-seq Data}
\vspace{0.4cm}
\hrule 

\vspace{1cm}
\Large
\begin{center}
Will Landau \\ $\quad$ \\
Department of Statistics \\
Iowa State University \\ $\quad$ \\
\today
\end{center}

\vfill
\large
\end{center}
\end{titlepage}

\newpage 
\pagestyle{fancy}
\setcounter{page}{1}
\pagenumbering{roman}
\tableofcontents 

\newpage
\setcounter{page}{1}
\pagenumbering{arabic}
%\fancyhead[C]{\thesection}

\begin{flushleft}

\section{The Model}

Let $y_{g,n}$ be the expression level of gene $g$  ($g = 1, \ldots, G$) in library $n$ ($n = 1, \ldots, N$). Let $\mu(n, \phi_g, \alpha_g, \delta_g)$ be the function given by:


\begin{align*}
\mu(n, \phi_g, \alpha_g, \delta_g) = \begin{cases}
\phi_g - \alpha_g & \text{ library $n$ is in treatment group 1} \\
\phi_g + \delta_g & \text{ library $n$ is in treatment group 2} \\
\phi_g + \alpha_g & \text{ library $n$ is in treatment group 3} \\
\end{cases}
\end{align*}

Then:

\begin{align*}
&y_{g,n} \sim \text{Poisson}(\exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \\
&\qquad c_n \sim \text{N}(0, \sigma^2_c) \\
& \qquad \qquad \sigma_c \sim \text{U}(0, \sigma_{c0}) \\
& \qquad \e_{g, n} \sim \text{N}(0, \sigma^2_g) \\
& \qquad \qquad \sigma_g^2 \sim \text{Inv-Gamma}\left (\text{shape} = \frac{d \cdot \tau^2}{2}, \ \text{rate} =  \frac{d}{2} \right) \\
& \qquad \qquad \qquad d \sim \text{U}(0, d_0) \\
& \qquad \qquad \qquad \tau^2 \sim \text{Gamma}(\tau^2 \mid \text{shape} = a_\tau, \text{rate} = b_\tau) \\
& \qquad \phi_g \sim \text{N}(\theta_\phi, \sigma_\phi^2) \\
& \qquad \qquad \theta_\phi \sim \text{N}(0, \gamma_{\phi }^2) \\
& \qquad \qquad \sigma_\phi \sim \text{U}(0, \sigma_{\phi 0}) \\
& \qquad \alpha_g \sim \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\theta_\alpha, \sigma_\alpha^2) \\
& \qquad \qquad \theta_\alpha \sim \text{N}(0, \gamma_{\alpha}^2) \\
& \qquad \qquad \sigma_\alpha \sim \text{U}(0, \sigma_{\alpha 0}) \\
& \qquad \qquad \pi_\alpha \sim \text{Beta}(a_{\alpha}, b_{\alpha}) \\
& \qquad \delta_g \sim \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0)  \text{N}(\theta_\delta, \sigma_\delta^2) \\
& \qquad \qquad \theta_\delta \sim \text{N}(0, \gamma_{\delta}^2) \\
& \qquad \qquad \sigma_\delta \sim \text{U}(0, \sigma_{\delta 0}) \\
& \qquad \qquad \pi_\delta \sim \text{Beta}(a_{\delta}, b_{\delta}) \\
\end{align*}

where:
\begin{itemize}
\item Independence is implied unless otherwise specified.
\item The parameters to the left of the ``$\sim$" are implicitly conditioned on the parameters to the right.
\end{itemize}

\section{Full Conditional Distributions}

Let $k(n)$ be the treatment group of library $n$. Then: 

\begin{align*}
p(c_n \mid \cdots) &= \prod_{g = 1}^G \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \cdot  \text{N}(c_n \mid 0, \sigma^2_c) \\
p \left (\sigma_c \mid \cdots \right ) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{N}(c_n \mid 0, \sigma_c^2) \cdot \text{U}(\sigma_c \mid 0, \sigma_{c0}) \\
p(\e_{g, n} \mid \cdots) &= \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \cdot \text{N}(\e_{g, n} \mid 0, \sigma_g^2) \\
p(\sigma_g^2 \mid \cdots) &= \prod_{n = 1}^N \text{N}(\e_{g, n} \mid 0, \sigma_g^2) \cdot \text{Inv-Gamma} \left ( \sigma_g^2 \mid \text{shape} = \frac{d \cdot \tau^2}{2}, \text{rate} = \frac{d}{2} \right ) \\ 
p(d \mid \cdots) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{Inv-Gamma} \left ( \sigma_g^2 \mid \text{shape} = \frac{d \cdot \tau^2}{2}, \text{rate} = \frac{d}{2} \right ) \cdot \text{U}(d \mid 0, d_0) \\ 
p(\tau^2 \mid \cdots) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{Inv-Gamma} \left ( \sigma_g^2 \mid \text{shape} = \frac{d \cdot \tau^2}{2}, \text{rate} = \frac{d}{2} \right ) \cdot \text{Gamma}(\tau^2 \mid \text{shape} = a_\tau, \text{rate} = b_\tau) \\
p(\phi_g \mid \cdots) &= \prod_{n = 1}^N \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \cdot \text{N}(\phi_g \mid \theta_\phi, \sigma_\phi^2) \\
p(\theta_\phi \mid \cdots ) & = \prod_{n = 1}^N \prod_{g = 1}^G \text{N}( \phi_g \mid \theta_\phi, \sigma_\phi^2)  \cdot \text{N}(\theta_\phi \mid 0, \gamma_{\phi}^2) \\
p(\sigma_\phi \mid \cdots ) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{N}( \phi_g \mid \theta_\phi, \sigma_\phi^2) \cdot \text{U}(\sigma_\phi \mid 0, \sigma_{\phi 0}) \\
p(\alpha_g \mid \cdots) &= \prod_{k(n) \ne 2}   \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \\
& \ \ \ \qquad \quad \times  ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) ) \\
p(\theta_\alpha \mid \cdots ) &= \prod_{k(n) \ne 2} \prod_{g = 1}^G  ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) ) \cdot \text{N}(\theta_\alpha \mid 0, \gamma_\alpha^2)   \\
p(\sigma_\alpha \mid \cdots ) & =  \prod_{k(n) \ne 2} \prod_{g = 1}^G  ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) ) \cdot \text{U}(\sigma_\alpha \mid 0, \sigma_{\alpha 0}) )   \\
p(\pi_\alpha \mid \cdots) &= \prod_{k(n) \ne 2} \prod_{g = 1}^G ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) )\cdot \text{Beta}(\pi_\alpha \mid a_\alpha, b_\alpha)  \\
\end{align*}

\begin{align*}
p(\delta_g \mid \cdots) &= \prod_{k(n) = 2}   \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \delta_g, \delta_g))) \\
& \ \ \ \qquad \quad \times  ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) ) \\
p(\theta_\delta \mid \cdots ) &= \prod_{k(n) = 2} \prod_{g = 1}^G  ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) ) \cdot \text{N}(\theta_\delta \mid 0, \gamma_\delta^2)   \\
p(\sigma_\delta \mid \cdots ) & =  \prod_{k(n) = 2} \prod_{g = 1}^G  ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) ) \cdot \text{U}(\sigma_\delta \mid 0, \sigma_{\delta 0})) \\
p(\pi_\delta \mid \cdots) &= \prod_{k(n) = 2} \prod_{g = 1}^G ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) )\cdot \text{Beta}(\pi_\delta \mid a_\delta, b_\delta)
\end{align*}


\section{Simplifying the Full Conditionals}

\subsection{$p(c_n \mid \cdots)$}

\begin{align*}
p(c_n \mid \cdots) &= \prod_{g = 1}^G \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \cdot  \text{N}(c_n \mid 0, \sigma^2_c)
\end{align*}

which is nothing immediately recognizable. I will sample from this distribution in a metropolis step using the kernel of this distribution (taking $\lambda_{g, n} = \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))$ ):


\begin{align*}
&\prod_{g = 1}^G  \lambda_{g, n}^{y_{g, n}}  \exp(- \lambda_{g, n}) \exp \left ( - \frac{c_n^2}{2 \sigma_c^2} \right ) \\
=&\prod_{g = 1}^G \exp \left (y_{g, n} \log \lambda_{g, n} - \lambda_{g, n}  - \frac{c_n^2}{2 \sigma_c^2} \right )  \\
=& \exp \left (\sum_{g = 1}^G  \left [ y_{g, n} \log \lambda_{g, n} - \lambda_{g, n} \right ] - \frac{G c_n^2}{2 \sigma_c^2} \right ) \\
\end{align*}

where the sum inside the exponent can be parallelized on the GPU.

\subsection {$p \left ( \frac{1}{\sigma_c^2} \mid \cdots \right ) $}

\begin{align*}
p \left ( \sigma_c \mid \cdots \right ) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{N}(c_n \mid 0, \sigma_c^2) \cdot \text{U}(\sigma_c \mid 0, \sigma_{c0})\\
    &\propto \prod_{n = 1}^N \prod_{g = 1}^G \frac{1}{\sqrt{\sigma_c^2 }}\exp \left (- \frac{c_n^2}{2 \sigma_c^2} \right )\cdot \text{I}(0 < \sigma_c < \sigma_{c0}) \\
    &= (\sigma_c^2)^{-NG/2} \exp \left ( - \frac{1}{\sigma_c^2}\frac{G}{2 } \sum_{n = 1}^N c_n^2 \right )\cdot \text{I}(0 < \sigma_c < \sigma_{c0}) \\
    \intertext{which, for constants $a$ and $b = \frac{G}{2} \sum_{n = 1}^N c_n^2$, can be written as}
    &a \cdot (\sigma_c^2)^{-NG/2} \exp \left ( - \frac{1}{\sigma_c^2} b\right )\text{I}(0 < \sigma_c^2 < \sigma_{c0}^2) \\
 \end{align*}
 
Transformation: let $z = g(\sigma_c) = {\sigma_c^2}$ so that $g \nv (z) ={\sqrt{z}}$ and:

\begin{align*}
p \left ( {\sigma_c^2} = z \mid \cdots \right ) &= p ( \sigma_c = g \nv (z) \mid \cdots) \left  |\frac{d g \nv (z)}{dz} \right | \\
&= a \cdot z^{-NG/2} \exp \left ( - \frac{1}{(\sqrt{z})^2} b\right ) I \left (0 < z < \sigma_{c0}^2 \right ) \left | \frac{1}{2} z^{-1/2 } \right | \\
&= \frac{a}{2} z^{-(NG/2 - 1/2 + 1)} \exp \left ( - \frac{1}{z} b\right ) I \left (0 < z < \sigma_{c0}^2 \right ) \\
&= \text{Inv-Gamma} \left (z \mid \text{shape} = \frac{NG - 1}{2}, \ \text{rate} = \frac{1}{b}\right ) I \left (0 < z < \sigma_{c0}^2 \right ) \\
\end{align*}

Recalling that $\frac{1}{b} = \frac{2}{G} \frac{1}{\sum_{n = 1}^N c_n^2}$,

\begin{align*}
p \left ( \frac{1}{\sigma_c^2} \mid \cdots \right) &= \text{Gamma} \left ( \frac{1}{\sigma_c^2} \mid \text{shape} = \frac{NG - 1}{2}, \ \text{rate} =\frac{2}{G} \frac{1}{\sum_{n = 1}^N c_n^2} \right )  I \left (\frac{1}{\sigma_c^2} < \frac{1}{\sigma_{c0}^2} \right ) \\
\end{align*}

 
\subsection{ $p(\e_{g, n} \mid \cdots) $}
 
 \begin{align*}
p(\e_{g, n} \mid \cdots) &= \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \cdot \text{N}(\e_{g, n} \mid 0, \sigma_g^2)
\end{align*}

which is nothing immediately recognizable. I will sample from this distribution in a metropolis step using the kernel:

\begin{align*}
&\lambda_{g, n}^{y_{g, n}} \exp(- \lambda_{g,n}) \exp \left ( - \frac{\e_{g, n}^2}{2 \sigma_g^2} \right ) \\
=& \exp \left (y_{g, n} \log \lambda_{g, n}- \lambda_{g,n}  - \frac{\e_{g, n}^2}{2 \sigma_g^2} \right)
\end{align*} 

where $\lambda_{g, n} = \exp (c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))$. The $\e_{g, n}$'s will be sampled in parallel across genes on the GPU. 


\subsection{$p \left (\frac{1}{\sigma_g^2} \mid \cdots \right )$}

\begin{align*}
p \left ({\sigma_g^2} \mid \cdots \right ) &= \prod_{n = 1}^N \text{N}(\e_{g, n} \mid 0, \sigma_g^2) \cdot \text{Inv-Gamma} \left ( {\sigma_g^2} \mid \text{shape} = \frac{d \cdot \tau^2}{2}, \text{rate} = \frac{d}{2} \right ) \\ 
&\propto \prod_{n = 1}^N (\sigma_g^{2})^{-1/2} \exp \left (- \frac{1}{ \sigma_g^2} \frac{\e_{g, n}^2}{2} \right ) \cdot \left ( { \sigma_g^2} \right )^{ -(d \tau^2/2 + 1)} \exp \left (- \frac{1}{ \sigma_g^2}\frac{2}{d} \right ) \\
&= \prod_{n = 1}^N (\sigma_g^2)^{-(d \tau^2 + 3)/2} \exp \left ( -\frac{1}{\sigma_g^2} \left (\frac{\e_{g, n}^2}{2} + \frac{2}{d} \right ) \right) \\
&=  (\sigma_g^2)^{-N(d \tau^2 + 3)/2} \exp \left ( -\frac{1}{\sigma_g^2} \left (\frac{2N}{d} + \frac{1}{2} \sum_{n = 1}^N \e_{g, n}^2 \right ) \right)
\end{align*}

The last line is the kernel of an inverse gamma distribution with shape parameter $N\frac{d \tau^2 + 3}{2} - 1$ and rate parameter $\left (\frac{2N}{d} + \frac{1}{2} \sum_{n = 1}^N \e_{g, n}^2 \right )^{-1} $. Hence:

\begin{align*}
p \left ( \frac{1}{\sigma_g^2} \mid \cdots \right ) = \text{Gamma} \left (\frac{1}{\sigma_g^2} \mid \text{shape} = N\frac{d \tau^2 + 3}{2} - 1, \  \text{rate} = \left (\frac{2N}{d} + \frac{1}{2} \sum_{n = 1}^N \e_{g, n}^2 \right )^{-1} \right)
\end{align*}

The $1/\sigma_g^2$'s will be sampled in parallel on the GPU.

\subsection{$p(d \mid \cdots)$}

\begin{align*}
p(d \mid \cdots) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{Inv-Gamma} \left ( \sigma_g^2 \mid \text{shape} = \frac{d \cdot \tau^2}{2}, \text{rate} = \frac{d}{2} \right ) \cdot \text{U}(d \mid 0, d_0) \\ 
& =\prod_{n = 1}^N \prod_{g = 1}^G  \left [ \Gamma \left ( \frac{d \tau^2}{2} \right ) \right ] ^{-1}  \left ( \frac{d}{2} \right )^{-d \tau^2 / 2} (\sigma_g^2)^{-(d \tau^2/2 + 1)} \exp \left ( - \frac{1}{\sigma_g^2} \frac{2}{d} \right )  I(0 < d < d_0) \\
&=  \left [ \Gamma \left ( \frac{d \tau^2}{2} \right ) \right ] ^{-GN}  \left ( \frac{d}{2} \right )^{-GNd \tau^2 / 2}  \prod_{n = 1}^N \prod_{g = 1}^G (\sigma_g^2)^{-(d \tau^2/2 + 1)} \exp \left ( - \frac{1}{\sigma_g^2} \frac{2}{d} \right )  I(0 < d < d_0) \\
&=  \left [ \Gamma \left ( \frac{d \tau^2}{2} \right ) \right ] ^{-GN}  \left ( \frac{d}{2} \right )^{-GNd \tau^2 / 2}  \prod_{g = 1}^G (\sigma_g^2)^{-N(d \tau^2/2 + 1)} \exp \left ( - \frac{N}{\sigma_g^2} \frac{2}{d} \right )  I(0 < d < d_0) \\
&=  \left [ \Gamma \left ( \frac{d \tau^2}{2} \right ) \right ] ^{-GN}  \left ( \frac{d}{2} \right )^{-GNd \tau^2 / 2}  \left ( \prod_{g = 1}^G \sigma_g^2 \right )^{-N(d \tau^2/2 + 1)} \exp \left ( - \frac{2N}{d} \sum_{g = 1}^G \frac{1}{\sigma_g^2} \right )  I(0 < d < d_0) \\
\end{align*}

I will sample $d$ with a metropolis step using the above density. Sums and products over $g$ ($g = 1, \ldots, G$) will be done in parallel on the GPU.









\subsection{$p(\tau^2 \mid \cdots)$}

\begin{align*}
p(\tau^2 \mid \cdots) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{Inv-Gamma} \left ( \sigma_g^2 \mid \text{shape} = \frac{d \cdot \tau^2}{2}, \text{rate} = \frac{d}{2} \right ) \cdot \text{Gamma}(\tau^2 \mid \text{shape} = a_\tau, \text{rate} = b_\tau) \\
p(\tau^2 \mid \cdots) &\propto \prod_{n = 1}^N \prod_{g = 1}^G \left [ \Gamma \left ( \frac{d \tau^2}{2} \right ) \right ] ^{-1}  \left ( \frac{d}{2} \right )^{-d \tau^2 / 2} (\sigma_g^2)^{-(d \tau^2/2 + 1)} \exp \left ( - \frac{1}{\sigma_g^2} \frac{2}{d} \right ) \\
& \qquad \qquad \times (\tau^2)^{a_\tau - 1} \exp \left ( - \tau^2 b_\tau \right ) \\
&= (\tau^2)^{a_\tau - 1} \left [ \Gamma \left ( \frac{d \tau^2}{2} \right ) \right ] ^{-GN}  \left ( \frac{d}{2} \right )^{-GN d \tau^2 / 2} \left ( \prod_{g = 1}^G \sigma_g^2 \right )^{-N(d \tau^2/2 + 1)} \exp \left (-GN \tau^2 b_\tau - \frac{2N }{d} \sum_{g = 1}^G \frac{1}{\sigma_g^2} \right ) 
\end{align*}

I will sample $\tau^2$ with a metropolis step using the above density. Sums and products over $g$ ($g = 1, \ldots, G$) will be done in parallel on the GPU.

















\begin{align*}
p(\phi_g \mid \cdots) &= \prod_{n = 1}^N \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \cdot \text{N}(\phi_g \mid \theta_\phi, \sigma_\phi^2) \\
p(\theta_\phi \mid \cdots ) & = \prod_{n = 1}^N \prod_{g = 1}^G \text{N}( \phi_g \mid \theta_\phi, \sigma_\phi^2)  \cdot \text{N}(\theta_\phi \mid 0, \gamma_{\phi}^2) \\
p(\sigma_\phi \mid \cdots ) &= \prod_{n = 1}^N \prod_{g = 1}^G \text{N}( \phi_g \mid \theta_\phi, \sigma_\phi^2) \cdot \text{U}(\sigma_\phi \mid 0, \sigma_{\phi 0}) \\
p(\alpha_g \mid \cdots) &= \prod_{k(n) \ne 2}   \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \alpha_g, \delta_g))) \\
& \ \ \ \qquad \quad \times  ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) ) \\
p(\theta_\alpha \mid \cdots ) &= \prod_{k(n) \ne 2} \prod_{g = 1}^G  ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) ) \cdot \text{N}(\theta_\alpha \mid 0, \gamma_\alpha^2)   \\
p(\sigma_\alpha \mid \cdots ) & =  \prod_{k(n) \ne 2} \prod_{g = 1}^G  ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) ) \cdot \text{U}(\sigma_\alpha \mid 0, \sigma_{\alpha 0}) )   \\
p(\pi_\alpha \mid \cdots) &= \prod_{k(n) \ne 2} \prod_{g = 1}^G ( \pi_\alpha \text{I}(\alpha_g = 0) +  (1- \pi_\alpha)\text{I}(\alpha_g \ne 0) \text{N}(\alpha_g \mid \theta_\alpha, \sigma_\alpha^2) )\cdot \text{Beta}(\pi_\alpha \mid a_\alpha, b_\alpha)  \\
p(\delta_g \mid \cdots) &= \prod_{k(n) = 2}   \text{Poisson}(y_{g, n} \mid \exp(c_n + \e_{g, n} + \mu(n, \phi_g, \delta_g, \delta_g))) \\
& \ \ \ \qquad \quad \times  ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) ) \\
p(\theta_\delta \mid \cdots ) &= \prod_{k(n) = 2} \prod_{g = 1}^G  ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) ) \cdot \text{N}(\theta_\delta \mid 0, \gamma_\delta^2)   \\
p(\sigma_\delta \mid \cdots ) & =  \prod_{k(n) = 2} \prod_{g = 1}^G  ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) ) \cdot \text{U}(\sigma_\delta \mid 0, \sigma_{\delta 0}) )   \\
p(\pi_\delta \mid \cdots) &= \prod_{k(n) = 2} \prod_{g = 1}^G ( \pi_\delta \text{I}(\delta_g = 0) +  (1- \pi_\delta)\text{I}(\delta_g \ne 0) \text{N}(\delta_g \mid \theta_\delta, \sigma_\delta^2) )\cdot \text{Beta}(\pi_\delta \mid a_\delta, b_\delta)
\end{align*}

\end{flushleft}
%\newpage 
%\bibliographystyle{plainnat} 
%\bibliography{}
\end{document}